"""Tests verifying the canonical feedback-path format generated by the
frontend (``index.html`` ResultsView) matches what the backend's
``is_valid_feedback_path`` accepts.

The frontend builds dot-notation paths with numeric indices — e.g.
``cards.0.cardMeta.cardDisplayName`` — never template (``[]``), JSON-pointer
(``/``), or wildcard (``*``) forms.  These tests pin the contract between
the ResultsView path construction and the backend validator so a drift on
either side is caught immediately.
"""

import re
import unittest
from pathlib import Path

from contracts.paths import is_valid_feedback_path

_INDEX_HTML = Path(__file__).resolve().parent.parent / "app" / "static" / "index.html"


class FrontendPathFormatTest(unittest.TestCase):
    """The 7 judged field types and their canonical path templates.

    Each tuple is (field description, path template with {i} for array index).
    These are the exact path strings ResultsView passes to ``submitFeedback``
    via the ``fieldPath`` prop on ``FieldRow`` / ``TxnCell``.
    """

    FIELD_TEMPLATES = [
        ("card name", "cards.{i}.cardMeta.cardDisplayName"),
        ("last four", "cards.{i}.cardMeta.lastFourDigit"),
        ("product family", "cards.{i}.cardMeta.productFamily"),
        ("network", "cards.{i}.cardMeta.network"),
        ("card credit limit", "cards.{i}.bigPicture.cardCreditLimit"),
        ("card avail credit limit", "cards.{i}.bigPicture.cardAvailableCreditLimit"),
        ("points earned", "rewards.pointsEarnedThisCycle"),
        ("closing points", "rewards.closingPoints"),
        ("program type", "rewards.programType"),
        ("opening points", "rewards.openingPoints"),
        ("points redeemed", "rewards.pointsRedeemedThisCycle"),
        ("points expiring 30", "rewards.pointsExpiringNext30Days"),
        ("points expiring 60", "rewards.pointsExpiringNext60Days"),
        ("bonus points", "rewards.bonusPointsThisCycle"),
        ("txn date", "transactions.{i}.date"),
        ("txn description", "transactions.{i}.description"),
        ("txn amount", "transactions.{i}.amount"),
        ("txn direction", "transactions.{i}.direction"),
        ("txn reward points", "transactions.{i}.rewardPointsOnThisTransaction"),
        ("issuer name", "statementMeta.issuerName"),
        ("statement date", "statementMeta.statementDate"),
        ("due date", "statementMeta.dueDate"),
        ("period start", "statementMeta.statementPeriodStart"),
        ("period end", "statementMeta.statementPeriodEnd"),
        ("total amount due", "statementLevelSummary.totalAmountDue"),
        ("total min amount due", "statementLevelSummary.totalMinimumAmountDue"),
        ("total credit limit", "statementLevelSummary.totalCreditLimit"),
        ("available credit limit", "statementLevelSummary.availableCreditLimit"),
    ]

    def test_all_canonical_paths_pass_validation(self) -> None:
        """Every path the frontend can generate must pass is_valid_feedback_path."""
        for _label, template in self.FIELD_TEMPLATES:
            for idx in (0, 1, 5, 14, 99):
                path = template.format(i=idx)
                with self.subTest(path=path):
                    self.assertTrue(
                        is_valid_feedback_path(path),
                        f"frontend generates {path!r} but backend rejects it",
                    )

    def test_rejected_path_forms(self) -> None:
        """Formats the frontend must NOT generate are rejected by the backend."""
        rejected = [
            "cards[].cardMeta.cardDisplayName",   # template bracket
            "cards.*.cardMeta.cardDisplayName",    # wildcard
            "/cards/0/cardMeta/cardDisplayName",   # JSON pointer
            "cards.01.cardMeta.lastFourDigit",     # leading zero
            "transactions[].amount",               # template bracket
            "transactions.01.date",                # leading zero
            "rewards.pointsEarned",                # unknown field
            "cards.0.cardMeta.isPrimaryCard",      # non-judged field
            "statementMeta.rawStatementId",        # non-judged field
            "transactions.0.txnType",             # non-judged field
            "transactions.0.currency",             # non-judged field
        ]
        for path in rejected:
            with self.subTest(path=path):
                self.assertFalse(
                    is_valid_feedback_path(path),
                    f"backend should reject {path!r}",
                )

    def test_index_html_contains_canonical_path_patterns(self) -> None:
        """index.html must contain the path patterns the frontend generates.

        This keeps the test in sync with the actual frontend code: if someone
        changes the path format in ResultsView without updating these
        patterns, the test fails.
        """
        html = _INDEX_HTML.read_text()
        # Indexed fields use JS template literals: `cards.${i}.cardMeta.cardDisplayName`
        # Scalar fields use plain strings: "rewards.closingPoints"
        required_patterns = [
            r"cards\.\$\{i\}\.cardMeta\.cardDisplayName",
            r"cards\.\$\{i\}\.cardMeta\.lastFourDigit",
            r"rewards\.pointsEarnedThisCycle",
            r"rewards\.closingPoints",
            r"transactions\.\$\{i\}\.date",
            r"transactions\.\$\{i\}\.description",
            r"transactions\.\$\{i\}\.amount",
        ]
        for pattern in required_patterns:
            with self.subTest(pattern=pattern):
                self.assertTrue(
                    re.search(pattern, html),
                    f"index.html missing path pattern: {pattern}",
                )


if __name__ == "__main__":
    unittest.main()
